backend:
    name: git-gateway
    branch: main # Change this to match your primary branch (e.g., master)

collections:
    - name: blog
      label: Blog
      folder: _posts
      create: true
      fields:
          - { name: title, label: Title, widget: string }
          - { name: date, label: Date, widget: datetime }
          # Add other fields as needed
